DELETE FROM "Teams";
DELETE FROM "Rooms";
DELETE FROM "People";
DELETE FROM "Employees";
DELETE FROM "BusinessPartners";
DELETE FROM "Facilities";
DELETE FROM "Bookings";
DELETE FROM "CostLogs";
DELETE FROM "Participants";
